"""empty message

Revision ID: 7d729397030a
Revises: 
Create Date: 2022-04-11 00:30:29.478870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d729397030a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='user_item_unique')
    )
    op.create_index(op.f('ix_user_item_item_id'), 'user_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_item_user_id'), 'user_item', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_item_user_id'), table_name='user_item')
    op.drop_index(op.f('ix_user_item_item_id'), table_name='user_item')
    op.drop_table('user_item')
    # ### end Alembic commands ###
